variable "region" {}
variable "redis_instance" {}
variable "redis_tier" {}
variable "redis_memory" {}
variable "vpc_id" {}
variable "redis_location" {}
variable "redis_alternative_location" {}
variable "redis_transit_encryption" {}
variable "redis_connect" {}
variable "redis_version" {}
variable "redis_replica_count" {}
variable "redis_replicas_mode" {}