apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-masq-agent
  namespace: kube-system
data:
  config: |
    {
      "nonMasqueradeCIDRs": [
        "10.29.237.0/24",       
        "10.10.0.0/16",         
        "192.40.0.0/16"        
      ],
      "masqLinkLocal": false,
      "resyncInterval": 60
    }
