name: NB Plan and Apply Terraform on GCP

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select a GCP Project to Deploy'
        required: true
        type: choice
        options:
          - dev
          - prod
      approve:
        description: 'Approve and Apply the Changes?'
        required: true
        type: boolean



jobs:
  plan_and_apply:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      SVC_KEY: ${{ secrets.GCP_DEV_INFRA_SVC }}
      # TF_VAR_company_name: ${{ vars.TF_VAR_company_name }}
      # TF_VAR_cloud_provider: ${{ vars.TF_VAR_cloud_provider }}
      # TF_VAR_gcp_project_id: ${{ vars.TF_VAR_gcp_project_id }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create service account key file
        run: echo "$SVC_KEY" > key

      - name: Initialize Terraform
        run: terraform init -backend-config="bucket=odi-kareco-dev-backend-bucket-${{ github.event.inputs.environment }}"

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform deployment
        run: terraform plan

      - name: Apply Terraform deployment
        if: ${{ github.event.inputs.approve == 'true' }}
        run: terraform apply --auto-approve